### ISSUE TITLE
Header bar does not scale custom image

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2-ui#19]
![image](https://cloud.githubusercontent.com/assets/2134901/10986198/43a7289a-8428-11e5-935d-bb3f7cb24bdb.png)

Note: This works the same for the header bar here as it does for the `core` version.

**Comment by nicolayr** [comment]
This _should_ be working already in the D2-UI component. Can you reproduce it in the header bar in the settings app?

The problem is that at the moment only the settings app is using the D2-UI component, while every other app is using a different version of the header bar where resizing isn't working like it should.
