### ISSUE TITLE
Do not use .bind() in React props

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2-ui#28]
Currently eslint will give a warning as we still use this in several places. But we should phase this out. 

@see
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md#no-bind-or-arrow-functions-in-jsx-props

**Comment by nicolayr** [comment]
That kinda sucks since React components written as ES6 classes don't function properly out of the box then.

The best fix would be to add `@autobind` decorators to the relevant methods - but apparently Babel 6 doesn't support that yet. So until Babel 6 gets support for `@autobind` we can:

1. Live with it
2. Use some [stop-gap Babel 6 plugin](https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy)

**Comment by nicolayr** [comment]
Eslint is basically useless for d2-ui at the moment since there are too many warnings to fix ;(
