### ISSUE TITLE
Modify group editor to allow changing of order of items in the selected list

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2-ui#47]
The right side should support ordering of the items. The items should be able to be moved up and down.

See the up and down arrows on the right of the screenshot.
![image](https://cloud.githubusercontent.com/assets/2134901/13952079/b26f285e-f034-11e5-9f74-397a6f693e8d.png)

This should also be to the `0.0.11-0` branch as it has to be back ported to the 2.22 version too.

**Comment by mortenoh** [comment]
Ideally you should be able to just drag the selected index/indices up and
down just the mouse.. but I'm not sure if you are using a simple <select />
or if there something more elegant there.

-- 
Morten Olav Hansen
Senior Engineer, DHIS 2
University of Oslo
http://www.dhis2.org

**Comment by Markionium** [comment]
Agreed that a drag-drop solution would be better.

Currently it's just a simple select. So for the "backported" version i guess we'll go with arrows.

**Comment by nicolayr** [comment]
I tried more flexible solutions for the group editor component, but since there can potentially be thousands of items in each box it was having an impact on performance. With select boxes performance wasn't an issue.

It should be possible to do drag & drop with select boxes too, though. Ideally it would be possible to drag items between the boxes as well as reordering within each box.

**Comment by Markionium** [comment]
`ordered` property on the properties in a schema is now available in 2.22 and trunk. When d2 adjusts for this we can use it to identify which collections need the ordering functionality. 

https://github.com/dhis2/d2/issues/70

**Comment by nicolayr** [comment]
Fixed in https://github.com/dhis2/d2-ui/commit/5f29837c2a717f491c675346932b580ccc82a51b
