### ISSUE TITLE
[OrgUnitTree] onClick

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2-ui#49]
Was emitting a object with an `id` and a `displayName` however for ModelCollectionProperty management it makes more sense for it to emit a `Model`

However currently it is emitting the same `Model` we should probably make the method emit a clone of the `Model` to make the sure the Model from props is not mutated outside after passing it to the `onClick`.

A convenience method to clone the `Model` would be nice to have in d2.

**Comment by nicolayr** [comment]
You're right, that definitely does make more sense, and not just for the `OrgUnitTree` component but for D2-UI in general.

I did it this way because I initially planned on supporting trees based on plain objects in addition to `d2.Model` instances, like we do for the `GroupEditor` component. But it probably makes for a better library if we just commit to using D2 models wherever it makes sense and don't try to support every possible use case in addition to our own.

**Comment by nicolayr** [comment]
This was implemented a while ago.
