### ISSUE TITLE
Add support for value formatting

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2-ui#5]
Turning valid values into equal values with different formatting. For example adding decimals to numbers, making relative URL's absolute, etc.

**Comment by nicolayr** [comment]
One possibility would be to do this using validators.

If a validator resolves successfully, but supplies a new value, replace the current value with the one supplied.

Thoughts, @Markionium ?

**Comment by Markionium** [comment]
Possibly but i think this is mixing concerns. And what happens if different validators return different values and those values are actually conflicting?

I would probably like it more if we had separate formatters that ran either before or after the validators. (I would presume before, so we can keep the validators pure, that only operate against the _true_ values.

For most cases a transformer is probably not important.

**Comment by nicolayr** [comment]
I agree. I'd say it's probably sufficient to have only one formatter, and it makes sense that it runs before the validators.

**Comment by nicolayr** [comment]
Hasn't turned out to be very important in the year since this issue was opened..
