### ISSUE TITLE
[FormBuilder] Don't update value from props if field is dirty

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2-ui#51]
If a form field has been changed by the user (eg. `state.fields[name].pristine = false`) when new props arrive, the current field value should be retained.

**Comment by nicolayr** [comment]
@Markionium - will this cause problems in the maintenance app? Was this the same issue you were experiencing?

**Comment by Markionium** [comment]
Might have been... I've got some changes to the FormBuilder pending, and added some tests. (These could break some of your stuff (although they shouldn't really)) The changes are not yet ready to be merged as I noticed (probably because of my changes) that when i changed to use the `props.fields[].value` as the source of truth, the pristine property is always true. 

We probably need a way to keep track of the original state of the field. However that original state would probably also need to be passed in as `field.originalValue` or so. We could do it on mount, however a component might not dismount and new fields could be passed. This would keep the wrong _old_ state.

**Comment by nicolayr** [comment]
All fields always have 2 possible values:

- The value of the underlying data - the props value
- The value of the field that hasn't yet been saved

Having a single source of truth in this case would lead to fields that can't be changed (eg. controlled fields that don't have a state update method).

The props should be the single source of truth for the underlying data, but the form itself needs to manage the state so that the new value can be validated before it's passed back to the `onUpdateField` callback.

I pushed a small change recently so that synchronous validators are now run for every `onChange` event, even for fields that have `changeEvent=onBlur`. The effect is that setting `changeEvent=onBlur` now only means that the async validators run on blur. Just like before, the `onUpdateField` callback is only called when the new value has passed all validators (sync and async).

There was also a bug that was preventing pristine state from being set correctly for each field. Essentially if the _current_ value of a field is the same as the underlying data value of the field, it means that the field is pristine (= unchanged). I've fixed this problem locally, and I've also changed `componentWillReceiveProps` so that the props value of a field (eg. the _underlying_ data) will only override the _current_ value of the field if the field is pristine (meaning the user hasn't made any changes to it that are not yet saved). This seems to have fixed the related issue in the settings app (https://github.com/dhis2/settings-app/issues/51).

I'll push this small change now, so you can see if it fixes your issue as well or if you need more comprehensive changes :)

**Comment by nicolayr** [comment]
Pushed now - see 476617c39cdaaedc2bb6b1bbbe1dfddc1dd6cfad

**Comment by nicolayr** [comment]
We'll change the FormBuilder API to address this.
