### ISSUE TITLE
Updating rxjs to v6 on the sharing-dialog package to enable tree-shaking 

### ISSUE THREAD

**Issue by paschalidi** [dhis2/d2-ui#590]
hello y'all 👋 

I am coming in with a friendly suggestion. 

I would like to update rxjs to version 6 in the [`sharing-dialog` package](https://github.com/dhis2/d2-ui/blob/master/packages/sharing-dialog/README.md). This way when we include the `sharing-dialog` to other projects it will come with a smaller bundle. The bundle is not that big at the moment but the rxjs dependency can be go down from ~140kbs to ~40kbs in my experience with tree-shaking. This might seem as a very small optimisation but since we most of the times operate in low resources areas this is still a win in my opinion. 

This is the bundle that we have at the moment in one of our apps from `sharing-dialog`. 
![image](https://user-images.githubusercontent.com/4181674/78881577-4fee9280-7a57-11ea-9c99-3b49e91fea02.png)

If you look closely you will see that now rxjs imports all the operators they are having. However we are using only a small portion of those and we therefore we dont need to import all of those. :) 

Let me know your thoughts! I will be happy to work on this, I have done the migration in the past and it is not that big of a problem. 🕊️

**Comment by amcgee** [comment]
Hi @paschalidi !  That would definitely be a nice improvement :-). Question though - would this be intended for 2.35 or to backport to earlier versions?  And which app(s) have you seen this affect?  We'd need to make sure the apps don't have incompatible `rxjs` versions anyway, otherwise we'll end up with duplication

If we want to backport this and it is a low-effort change (I think it should be, there's very little use of `rxjs` in this package) then I say go for it!  Either upgrade `rxjs` or (perhaps better?) remove the tiny amount of `rxjs` we use here and get rid of the dependency altogether - 

If this is targeted for 2.35 we will be [rewriting this component](https://jira.dhis2.org/browse/TECH-274) using @cooper-joe's new designs and `ui-core` (removing `rxjs`), so it might be worth working on that effort instead? - I will be starting this shortly, would be very happy to work with you on it if you want to help out!

**Comment by amcgee** [comment]
See https://github.com/dhis2/ui/pull/24

**Comment by paschalidi** [comment]
As you said @amcgee, it makes more sense to finish the widget than updating this one. I didnt take into account that the release circle. Will pick something from the list you mentioned. Thanks for including me in this!!
