### ISSUE TITLE
Right/middle click does not work as expected in menu bar

### ISSUE THREAD

**Issue by mortenoh** [dhis2/d2-ui#74]
It's currently not possible to right click on an menu item, and open in a new tab.. without also triggering an action on the current tab.. which means you end up with the same page in current + new tab... i consider this a bug, it's very useful to be able to do this.. and a common pattern

**Comment by nicolayr** [comment]
This happens because the menu bar uses a custom click handler that treats all mouse buttons equally and overrides the default behaviour of the browser.

@Markionium is there any particular reason why we need to do this? If not I suggest we make stick with the default behaviour, which is also what users expect.

**Comment by Markionium** [comment]
There was but i don't think that still applies. I'll test and change it :)
