### ISSUE TITLE
[OrgUnitTree] Org units are not sorted below level 2

### ISSUE THREAD

**Issue by larshelge** [dhis2/d2-ui#85]
Org units in the org unit tree are not sorted below level 2. Child org units of a parent should be sorted alphabetically at all levels.

![iy](https://cloud.githubusercontent.com/assets/908206/18851932/7a3ee0d4-843e-11e6-876d-e11f45dd810c.png)

**Comment by nicolayr** [comment]
This is caused by the fact that the query for fetching child org-units returns the list unordered, and passing `order=displayName:asc` to the API endpoint doesn't seem to have any effect.

@larshelge We can fix this by sorting the returned org units on the client, but it might be better to fix it in the backend?

The query used to fetch child org units is:
`/api/organisationUnits/<parent uid>?fields=children[id,displayName,children::isNotEmpty,path,parent]`
